// <auto-generated />
namespace Dayboi_Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_11132018_2250 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_11132018_2250));
        
        string IMigrationMetadata.Id
        {
            get { return "201811131550490_update_11132018_2250"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
